services:
  drive-cache:
    build: .
    container_name: drive-cache
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/opt/drive-cache/data
    networks:
      - caddy_default
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


networks:
  caddy_default:
    external: true
